package(default_visibility = ["//visibility:public"])

java_library(
    name = "pokemon",
    srcs = glob(["*.java"]),
    deps = [
        "//main/java/com/jbrown/pokemon/controllers",
        "//main:autovalue",
        "//external:spark",
    ],
)


