package(default_visibility = ["//visibility:public"])

java_library(
    name = "battle",
    srcs = glob(["*.java"]),
    deps = [
        "//main/java/com/jbrown/pokemon/entities",
        "//main/java/com/jbrown/pokemon/enums",
    ],
)


