package(default_visibility = ["//visibility:public"])

java_library(
    name = "controllers",
    srcs = glob(["*.java"]),
    deps = [
      "//main/java/com/jbrown/pokemon/entities/silver",
      "//main/java/com/jbrown/pokemon/enums",
      "//external:guava",
      "//external:gson",
    ],
)
