package(default_visibility = ["//visibility:public"])

java_library(
    name = "entities",
    srcs = glob(["*.java"]),
    deps = [
        "//main:autovalue",
        "//main/java/com/jbrown/pokemon/entities/silver",
        "//main/java/com/jbrown/pokemon/enums",
    ],
)

