java_test(
    name = "DamagingMoveExecutorTest",
    srcs = ["DamagingMoveExecutorTest.java"],
    deps = [
        "//main/java/com/jbrown/pokemon/battle",
        "//main/java/com/jbrown/pokemon/entities",
        "//main/java/com/jbrown/pokemon/entities/silver",
        "//main/java/com/jbrown/pokemon/enums",
        "//external:junit",
    ],
)
